language: python
env:
    - TOXENV=py26-django11
    - TOXENV=py26-django12
    - TOXENV=py26-django13
    - TOXENV=py26-django14
    - TOXENV=py26-django15
    - TOXENV=py26-django16

    - TOXENV=py27-django14
    - TOXENV=py27-django15
    - TOXENV=py27-django16
    - TOXENV=py27-django17
    - TOXENV=py27-django18
    - TOXENV=py27-django18-cdecimal
    - TOXENV=py27-django111
    - TOXENV=py27-django111-cdecimal

    - TOXENV=py33-django17
    - TOXENV=py33-django18
    - TOXENV=py33-django18-cdecimal

    - TOXENV=py34-django15
    - TOXENV=py34-django16
    - TOXENV=py34-django17
    - TOXENV=py34-django18
    - TOXENV=py34-django18-cdecimal
    - TOXENV=py34-django111
    - TOXENV=py34-django111-cdecimal

    - TOXENV=py35-django18
    - TOXENV=py35-django18-cdecimal
    - TOXENV=py35-django111
    - TOXENV=py35-django111-cdecimal

    - TOXENV=py36-django111
    - TOXENV=py36-django111-cdecimal

    - TOXENV=pypy-django14
    - TOXENV=pypy-django15
    - TOXENV=pypy-django16
    - TOXENV=pypy-django17
    - TOXENV=pypy-django18
    - TOXENV=pypy-django111

    - TOXENV=pypy3-django17
    - TOXENV=pypy3-django18
    - TOXENV=pypy3-django111

    - TOXENV=cov
matrix:
    allow_failures:
        - env: TOXENV=cov
install:
    - pip install --quiet tox
script:
    - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet coveralls;
      coveralls;
      fi
